// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiaiManager.Api.Data;

#nullable disable

namespace ShiaiManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class MakeAthleteGradeOptional
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ShiaiManager.Api.Data.AthleteRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");
                b.Property<int>("BirthYear").HasColumnType("INTEGER");
                b.Property<Guid>("ClubId").HasColumnType("TEXT");
                b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("TEXT");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(60).HasColumnType("TEXT");
                b.Property<string>("Gender").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<int?>("Grade").HasColumnType("INTEGER");
                b.Property<int?>("LastFightDurationSeconds").HasColumnType("INTEGER");
                b.Property<DateTimeOffset?>("LastFightEndedAtUtc").HasColumnType("TEXT");
                b.Property<string>("LastName").IsRequired().HasMaxLength(60).HasColumnType("TEXT");
                b.Property<string>("LicenseId").HasMaxLength(40).HasColumnType("TEXT");
                b.Property<Guid>("TournamentId").HasColumnType("TEXT");
                b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("TEXT");
                b.Property<decimal?>("WeightKg").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ClubId");
                b.HasIndex("TournamentId");
                b.ToTable("Athletes", (string)null);
            });

            modelBuilder.Entity("ShiaiManager.Api.Data.ClubRecord", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Clubs", (string)null);
            });

            modelBuilder.Entity("ShiaiManager.Api.Data.TournamentRecord", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Tournaments", (string)null);
            });

            modelBuilder.Entity("ShiaiManager.Api.Data.AthleteRecord", b =>
            {
                b.HasOne("ShiaiManager.Api.Data.ClubRecord", "Club")
                    .WithMany()
                    .HasForeignKey("ClubId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("ShiaiManager.Api.Data.TournamentRecord", "Tournament")
                    .WithMany()
                    .HasForeignKey("TournamentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Club");
                b.Navigation("Tournament");
            });
#pragma warning restore 612, 618
        }
    }
}